config/routes.rb
Rails.application.routes.draw do
  
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  root to: "posts#index"

  devise_for :users
  resources :friends, only: [:index, :create]
  resources :posts, only: [:index, :new, :create, :update, :destroy, :edit]
  resources :requests, only: [:index, :update, :destroy]
  
  get 'get_followings', to: "home#get_followings"
  get 'get_followers', to: "home#get_followers"
  get 'unfriend', to: "home#unfriend"
  delete 'unfriend', to: "home#unfriend"
  get 'my_post', to: "posts#my_post"

end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/friend.rb
class Friend < ApplicationRecord
  scope :request, ->(follower_id) { Relationship.where(follower_id: follower_id, following_id: current_user.id, request_approved: false)}
end

app/models/post.rb
class Post < ApplicationRecord
  # has_many :userposts
  belongs_to :user

  scope :find_post, ->(id) { Post.find(id) }
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  # The user giving the follow
  belongs_to :follower, foreign_key: :follower_id, class_name: "User"

  # The user being followed
  belongs_to :following, foreign_key: :following_id, class_name: "User"
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :confirmable, :lockable, :trackable

  # Will return an array of follows for the given user instance
  has_many :received_follows, foreign_key: :following_id, class_name: "Relationship"

  # Will return an array of users who follow the user instance
  has_many :followers, through: :received_follows, source: :follower

  # returns an array of follows a user gave to someone else
  has_many :given_follows, foreign_key: :follower_id, class_name: "Relationship"
  
  # returns an array of other users who the user has followed
  has_many :followings, through: :given_follows, source: :following

  # has_many :userposts, dependent: :destroy
  has_many :posts, dependent: :destroy
end

app/models/userpost.rb
class Userpost < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/friends_controller.rb
class FriendsController < ApplicationController

  def index
    user = User.all()
    following = current_user.followings
    @users = user - following - [current_user]
  end

  def create
    user = User.find(params[:id])
    rel = Relationship.new(follower_id: current_user.id, following_id: params[:id], request_approved: false)
    if rel.save
      redirect_to friends_path
    end
  end

  # def friend_request
  #   requests = Relationship.where(following_id: current_user.id, request_approved: false)
  #   @requests = []
  #   requests.each { |r| @requests.append(r.follower)}
  #   # user = User.joins(:relationship).where(following_id: current_user.id)
  # end

  # def accept_request
  #   request = Relationship.where(follower_id: params[:follower_id], following_id: current_user.id, request_approved: false)
  #   if request.update(request_approved: true)
  #     redirect_to friendRequest_path
  #   end
  # end

  # def reject_request
  #   # request = Relationship.where(follower_id: params[:follower_id], following_id: current_user.id, request_approved: false)
  #   request = Friend.request(params[:follower_id])
  #   if Relationship.destroy(request.ids)
  #     redirect_to friendRequest_path
  #   end
  # end


end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def get_followings
    # followings = Relationship.where(follower_id: current_user.id, request_approved: true)
    # following = []
    # followings.each { |f| following.append(f.following)}
    # @followings = following

    @followings = Relationship.joins(:follower).where("follower_id=?  and request_approved =true",current_user.id)
    @followings = @followings.map{ |follow| follow.following}
  end

  def get_followers
    # followers = Relationship.where(following_id: current_user.id, request_approved: true)
    # follower = []
    # followers.each { |f| follower.append(f.follower)}
    # @followers = follower

    @followers = Relationship.joins(:follower).where("following_id=?  and request_approved =true",current_user.id)
    @followers = @followers.map{ |follow| follow.follower}
  end

  def unfriend
    friend = Relationship.where(follower_id: current_user.id, following_id: params[:following_id], request_approved: true)
    if Relationship.destroy(friend.ids)
      redirect_to get_followings_path
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  #get all post
  def index
    # rel = Relationship.where(follower_id: current_user.id, request_approved: true)
    # followings = []
    # for r in rel
    #   followings.append(User.find(r.following_id))
    # end
    
    # @posts = []
    # for following in followings
    #   @posts.concat(following.posts)
    # end
    
    followings = Relationship.joins(:follower).where("follower_id=?  and request_approved =true",current_user.id)
    @posts = followings.map{ |follow| follow.following.posts}
    @posts = @posts.first
  end

  def new
  end

  # create new post
  def create
    post = Post.new(title: params[:post][:title], description: params[:post][:description])
    post.user = current_user
    if post.save
      redirect_to root_path
    end
  end

  # update post
  def update
    @post = Post.find(params[:id])
    @post.update(title: params[:post][:title], description: params[:post][:description], imageUrl: params[:imageUrl])
    if @post.save
      redirect_to my_post_path
    end
  end

  # delete post
  def destroy
    # post = Post.find(params[:id])
    post = Post.find_post(params[:id])
    if post.destroy
      redirect_to my_post_path
    end
  end

  def edit
    @post = Post.find_post(params[:id])
  end

  def my_post
    @posts = Post.where(user_id: current_user.id)
  end

end

app/controllers/requests_controller.rb
class RequestsController < ApplicationController

  before_action :set_request, only: %i[update destroy]

  def index
    # requests = Relationship.where(following_id: current_user.id, request_approved: false)
    # @requests = []
    # requests.each { |r| @requests.append(r.follower)}
    @requests = Relationship.joins(:follower).where("following_id=?  and request_approved =false",current_user.id)
    @requests = @requests.map { |user| user.follower}
  end

  def update
    if @request.update(request_approved: true)
      render "index"
    end
  end

  def destroy
    if Relationship.destroy(@request.ids)
      render "index"
    end
  end

  private 

    def set_request
      @request = Relationship.where(follower_id: params[:id], following_id: current_user.id, request_approved: false)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/post_helper.rb
module PostHelper
end

app/views/friends/create.html.erb
<p>create friends</p>

app/views/friends/index.html.erb
<% if @users %>
  <% for user in @users %>
    <%= user.email %> <span> <%= link_to "Send Request", friends_path(id: user.id), method: :post %></span><br />
  <% end %>
<% end %>

app/views/home/add_friends.html.erb
<span>Friend Request Sent</span>

app/views/home/find_friends.html.erb
<% if @users %>
  <% for user in @users %>
    <%= user.email %> <span> <%= link_to "Send Request", addFriends_path(id: user.id) %></span><br />
  <% end %>
<% end %>

app/views/home/get_followers.html.erb
<% for friend in @followers %>
  <%= friend.email %><br />
<% end %>

app/views/home/get_followings.html.erb
<% for friend in @followings %>
  <%= friend.email %> <span><%= link_to "Unfriend", unfriend_path(following_id: friend.id), data: {confirm: 'are you sure'}%></span><br />
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MiniFacebook</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

    <% if user_signed_in? %>
    <nav class="navbar navbar-expand-lg bg-body-tertiary">
      <div class="container-fluid">
        <%= link_to current_user.email, root_path, class: "navbar-brand" %>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
          <ul class="navbar-nav">
            
            <li class="nav-item">
              <%= link_to "Find Friends", friends_path, class: "nav-link active" %>
            </li>
            <li class="nav-item">
              <%= link_to "Following ", get_followings_path, class: "nav-link active" %>
            </li>
            <li class="nav-item">
              <%= link_to "Followers", get_followers_path, class: "nav-link active" %>
            </li>
            <li class="nav-item">
              <%= link_to "Friend Requests", requests_path, class: "nav-link active" %>
            </li>
            <li class="nav-item">
              <%= link_to "Create Post", new_post_path, class: "nav-link active" %>
            </li>
            <li class="nav-item">
              <%= link_to "My Post", my_post_path, class: "nav-link active" %>
            </li>
            <li class="nav-item">
              <%= link_to "Sign out", destroy_user_session_path, method: :delete, class: "nav-link active text-danger" %>
            </li>
            
          </ul>
        </div>
      </div>
    </nav>
      
    <% end %>

    <%= yield %>
  </body>
</html>

app/views/posts/edit.html.erb
<h1>Update Posts</h1>
<%= form_with(model: @post, local: true) do |form| %>

  <p>
    <%= form.label :title %>
    <br/>
    <%= form.text_field :title %>
  </p>

  <p>
    <%= form.label :description %><br/>
    <%= form.text_area :description %>
  </p>
  
  <p>
    <%= form.submit %>
  </p>
<% end %>

app/views/posts/index.html.erb
<% for post in @posts %>
  <div>
    <span>
      <h3>
        <%= post.user.email%>
      </h3>
      <b>
        <%= post.title %>
      </b>
      <% if post.imageUrl %>
        <img src="<%= post.imageUrl %>">
      <% end %>
      <p>
        <%= post.description %>
      </p>
    </span>
    <% if post.user.id == current_user.id %>
      <span>
        <%= link_to "Delete Post", post_path(id: post.id), method: :delete %>
      </span>
      <span>
        <%= link_to "Edit Post", edit_post_path(id: post.id) %>
      </span>
    <% end %>
  </div>
<% end %>

app/views/posts/my_post.html.erb
<% if @posts %>
  <% for post in @posts %>
    <div>
      <span>
        <h3>
          <%= post.user.email%>
        </h3>
        <b>
          <%= post.title %>
        </b>
        <% if post.imageUrl %>
          <img src="<%= post.imageUrl %>">
        <% end %>
        <p>
          <%= post.description %>
        </p>
      </span>
      <% if post.user.id == current_user.id %>
        <span>
          <%= link_to "Delete Post", post_path(id: post.id), method: :delete %>
        </span>
        <span>
          <%= link_to "Edit Post", edit_post_path(id: post.id) %>
        </span>
      <% end %>
    </div>
  <% end %>
<% end %>

app/views/posts/new.html.erb
<h1>Create new Posts</h1>
<%= form_with url: posts_path , scope: :post, local: true do |form| %>

  <p>
    <%= form.label :title %>
    <br/>
    <%= form.text_field :title %>
  </p>

  <p>
    <%= form.label :description %><br/>
    <%= form.text_area :description %>
  </p>
  
  <p>
    <%= form.submit %>
  </p>
<% end %>

app/views/requests/index.html.erb
<% if @requests %>
  <% for request in @requests %>
    <%= request.email %> 
    <span> <%= link_to "Accept", request_path(id: request.id), method: :patch %></span> 
    <span> <%= link_to "Reject", request_path(id: request.id), method: :delete%></span><br />
  <% end %>
<% end %>